image: rust:latest

stages:
  - test
  - build

rust-latest:
  stage: test
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

latest-artifact:
  stage: build
  script:
    - cargo build --release
    - mkdir public
    - mv target/release/zeno public/
    - mv data/ public/
    - strip public/zeno
  artifacts:
    expire_in: 1 yrs
    paths:
      - public/
  only:
    - master
