[package]
name = "zeno"
version = "0.0.0"
authors = ["Owez <owez@scalist.net>"]
edition = "2018"

[dependencies]

[dependencies.cursive] # Default ncurses backend is insecure
git = "https://github.com/gyscos/cursive"
default-features = false
features = ["crossterm-backend"]
