[package]
name = "zeno"
version = "0.0.0"
authors = ["Owez <owez@scalist.net>"]
edition = "2018"

[dependencies]

[dependencies.cursive] # TUI Library
version = "0.13"
default_features = false
features = ["termion-backend"] # Default is insecure
